import { readFile, readdir } from "node:fs/promises";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const modelsDirectory = resolve(root, "public/models");
// Meshopt's 14-bit position quantization can introduce <1mm error at this scale.
const epsilon = 0.001;

/** Application-space contracts: translation and axis-aligned dimensions in meters. */
const contracts = {
  "court.glb": {
    "ENV_Court_Surface": [[0, -0.13, 0], [8.2, 0.25, 12.4]],
    "ENV_Net_Mesh": [[0, 0.535, 0], [7.9, 1.07, 0.025]],
    "ENV_Net_PostEast": [[4, 0.59, 0], [0.09, 1.18, 0.09]], "ENV_Net_PostWest": [[-4, 0.59, 0], [0.09, 1.18, 0.09]],
    "ENV_Net_TopBand": [[0, 1.07, 0], [8, 0.06, 0.06]],
    "LINE_BaselineNorth": [[0, 0.015, 5.8], [7.7, 0.025, 0.07]], "LINE_BaselineSouth": [[0, 0.015, -5.8], [7.7, 0.025, 0.07]],
    "LINE_CenterNorth": [[0, 0.015, 1.05], [0.055, 0.025, 2.1]], "LINE_CenterSouth": [[0, 0.015, -1.05], [0.055, 0.025, 2.1]],
    "LINE_ServiceNorth": [[0, 0.015, 2.1], [5, 0.025, 0.055]], "LINE_ServiceSouth": [[0, 0.015, -2.1], [5, 0.025, 0.055]],
    "LINE_SidelineEast": [[3.85, 0.015, 0], [0.07, 0.025, 11.6]], "LINE_SidelineWest": [[-3.85, 0.015, 0], [0.07, 0.025, 11.6]],
  },
  "stadium-shell.glb": {
    "ENV_Stadium_BackdropNorth": [[0, 1.7, 8], [15, 3.4, 0.3]], "ENV_Stadium_BackdropSouth": [[0, 1.7, -8], [15, 3.4, 0.3]],
    "ENV_Stadium_RiserEast": [[7.1, 0.55, 0], [0.7, 1.1, 16]], "ENV_Stadium_RiserWest": [[-7.1, 0.55, 0], [0.7, 1.1, 16]],
  },
  "props.glb": {
    "ENV_Benches_North": [[-5.15, 0.35, 4.2], [2.3, 0.4, 0.55]], "ENV_Benches_South": [[-5.15, 0.35, -4.2], [2.3, 0.4, 0.55]],
    "ENV_UmpireChair_Back": [[4.65, 1.55, 0.52], [0.55, 0.7, 0.09]], "ENV_UmpireChair_LegEast": [[4.85, 0.52, 0.35], [0.08, 1.2, 0.08]],
    "ENV_UmpireChair_LegWest": [[4.45, 0.52, 0.35], [0.08, 1.2, 0.08]], "ENV_UmpireChair_Seat": [[4.65, 1.05, 0.35], [0.55, 0.18, 0.45]],
  },
  "scoreboard.glb": {
    "ENV_Scoreboard_Display": [[0, 2.5, 7.64], [2.35, 1.08, 0.03]], "ENV_Scoreboard_Frame": [[0, 2.5, 7.76], [2.7, 1.45, 0.16]],
  },
};

function inspectGlb(buffer) {
  if (buffer.readUInt32LE(0) !== 0x46546c67 || buffer.readUInt32LE(4) !== 2) throw new Error("Not a GLB 2.0 asset.");
  if (buffer.readUInt32LE(8) !== buffer.byteLength) throw new Error("GLB length header does not match file length.");
  if (buffer.readUInt32LE(16) !== 0x4e4f534a) throw new Error("GLB has no JSON chunk.");
  return JSON.parse(buffer.subarray(20, 20 + buffer.readUInt32LE(12)).toString("utf8").trim());
}

function sameVector(actual, expected) {
  return actual?.length === expected.length && actual.every((value, index) => Math.abs(value - expected[index]) <= epsilon);
}

function decodedBounds(accessor) {
  if (!accessor.normalized) return [accessor.min, accessor.max];
  const divisor = accessor.componentType === 5122 ? 32767 : accessor.componentType === 5120 ? 127 : 1;
  return [accessor.min.map((value) => Math.max(-1, value / divisor)), accessor.max.map((value) => value / divisor)];
}

for (const [file, contract] of Object.entries(contracts)) {
  const json = inspectGlb(await readFile(resolve(modelsDirectory, file)));
  const nodes = new Map(json.nodes.map((node) => [node.name, node]));
  const expectedNames = Object.keys(contract).sort();
  const actualNames = [...nodes.keys()].sort();
  if (JSON.stringify(actualNames) !== JSON.stringify(expectedNames)) throw new Error(`${file} has unexpected, missing, or autogenerated node names.`);
  if (actualNames.some((name) => name.startsWith("Cube"))) throw new Error(`${file} contains autogenerated Cube node names.`);
  for (const [name, [translation, dimensions]] of Object.entries(contract)) {
    const node = nodes.get(name);
    if (!sameVector(node.translation, translation)) throw new Error(`${name} does not match its application-space translation.`);
    if (node.rotation) throw new Error(`${name} has an unexpected rotation.`);
    const primitive = json.meshes[node.mesh].primitives[0];
    const accessor = json.accessors[primitive.attributes.POSITION];
    const [localMin, localMax] = decodedBounds(accessor);
    const scale = node.scale ?? [1, 1, 1];
    const actualDimensions = localMax.map((value, index) => (value - localMin[index]) * scale[index]);
    if (!sameVector(actualDimensions, dimensions)) throw new Error(`${name} mesh dimensions do not match the contract.`);
    const actualMin = localMin.map((value, index) => value * scale[index] + node.translation[index]);
    const actualMax = localMax.map((value, index) => value * scale[index] + node.translation[index]);
    const expectedMin = translation.map((value, index) => value - dimensions[index] / 2);
    const expectedMax = translation.map((value, index) => value + dimensions[index] / 2);
    if (!sameVector(actualMin, expectedMin) || !sameVector(actualMax, expectedMax)) throw new Error(`${name} world bounds do not match the contract.`);
  }
  if (json.images?.length) throw new Error(`${file} must not contain unbudgeted raster images.`);
  if (!json.extensionsUsed?.includes("EXT_meshopt_compression")) throw new Error(`${file} is missing required Meshopt compression.`);
}
const expected = Object.keys(contracts).length;
const present = (await readdir(modelsDirectory)).filter((file) => file.endsWith(".glb")).length;
if (present !== expected) throw new Error(`Expected ${expected} production GLBs; found ${present}.`);
console.log(`Validated ${expected} production GLBs: exact names, transforms, dimensions, world bounds, Meshopt, and texture policy.`);
